# "Numpy introduction exercices solutions "

- toc: false 
- comments: false
- layout: post


## Exercise 1 - Element-wise addition of 2 numpy arrays
Given are 2 similar dimensional numpy arrays, how to get a numpy array output in which every element is an element-wise sum of the 2 numpy arrays?

In [10]:

a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([10,11,12])

c = a + b

print(c)

[[11 13 15]
 [14 16 18]]


## Exercise 2 - Multiplying a matrix (numpy array) by a scalar
Given a numpy array (matrix), how to get a numpy array output which is equal to the original matrix multiplied by a scalar?EXERCISE 2 - Multiplying a matrix (numpy array) by a scalar

In [11]:
a = np.array([[1,2,3],
              [4,5,6]])

b = 2*a # multiplying the numpy array a(matrix) by 2

print(b)

[[ 2  4  6]
 [ 8 10 12]]


##Exercise 3 - Array re-dimensioning
Convert a 1-D array to a 3-D array

In [14]:
import numpy as np

b = [x for x in range(27)]
print(b)

a = np.array(b)

o = a.reshape((3,3,3))

print(o)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


##Exercise 4 - Array datatype conversion
Convert all the elements of a numpy array from float to integer datatype

In [15]:
a = np.array([[2.5, 3.8, 1.5],
              [4.7, 2.9, 1.56]])

o = a.astype('int')

print(o)

[[2 3 1]
 [4 2 1]]


## Exercise 5 - Custom Sequence Generation
Generate a sequence of numbers :

    [  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34 36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70 72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]

In [4]:
import numpy as np
list_of_numbers = [x for x in range(0, 101, 2)]

o = np.array(list_of_numbers)

print(o)


[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


## Exercise 6 - Getting the positions (indexes) where elements of 2 numpy arrays match
From 2 numpy arrays, extract the indexes in which the elements in the 2 arrays match

In [21]:
a = np.array([1,2,3,4,5])

b = np.array([1,3,2,4,150])


b[np.where(a == 5)]

array([150])